package main

import (
	T "html/template"
	"os"
)

const (
	template = `
<html>
    <head>
        <link href:="http://fonts.googleapis.com/css?family={{.FontName}}" rel="stylesheet" type="text/css">
    </head>
    <body>
        {{.Script}}
        {{.Safe}}
    </body>
</html>
    `
)

func main() {
	context := struct {
		FontName string
		Script   string
		Safe     T.HTML
	}{
		"Pathway Gothic One",
		"<script>alert('i haz ur cookies');</script>",
		T.HTML("<script>console.log('generated by application')</script>"),
	}

	t := T.Must(T.New("thestdlib").Parse(template))
	t.Execute(os.Stdout, context)
}

/* Output:
<html>
    <head>
        <link href:="http://fonts.googleapis.com/css?family=Pathway Gothic One" rel="stylesheet" type="text/css">
    </head>
    <body>
        &lt;script&gt;alert(&#39;i haz ur cookies&#39;);&lt;/script&gt;
        <script>console.log('generated by application')</script>
    </body>
</html>
*/
